# Решите следующий комплекс задач. Составьте систему линейных уравнений и решите ее с помощью модуля numpy


Вкладчик положил 50000 условных единиц на три разных счета в три разных банка. По первому счету выплаты составят 5% годовых, по второму – 7% годовых и по третьему 6% годовых. Известно, что через год вкладчик получил по процентам сумму в 2250 у.е. с первого и второго банка и сумму в 1400 у.е. с первого и третьего банка. Сколько условных единиц он положил на каждый счет изначально?

In [3]:
import numpy as np

In [25]:
coefficient = np.array([[1, 1, 1],[0.05, 0.07, 0],[0.05, 0, 0.06]], dtype=float)
coefficient


array([[1.  , 1.  , 1.  ],
       [0.05, 0.07, 0.  ],
       [0.05, 0.  , 0.06]])

In [26]:
money = np.array([50000, 2250, 1400], dtype=float)
money

array([50000.,  2250.,  1400.])

In [27]:
deposits = np.linalg.solve(coefficient, money)
deposits

array([10000., 25000., 15000.])

In [29]:
print(f'Deposit in first bank: {deposits[0]}')
print(f'Deposit in second bank: {deposits[1]}')
print(f'Deposit in third bank: {deposits[2]}')

Deposit in first bank: 10000.0
Deposit in second bank: 25000.0
Deposit in third bank: 15000.0


На складе хранятся мобильные телефоны iPhone 6, iPhone 11, iPhone 12 моделей. Всего 1328 экземпляра. Моделей iPhone 6 на 120 меньше, чем моделей iPhone 11, и на 100 больше, чем моделей iPhone 12. Сколько моделей каждого вида на складе?

In [41]:
models = np.array([[1, 1, 1], [1, -1, 1], [1, 1, -1]], dtype=int)
models

array([[ 1,  1,  1],
       [ 1, -1,  1],
       [ 1,  1, -1]])

In [42]:
count = np.array([1238, 100, 12], dtype=int)
count

array([1238,  100,   12])

In [43]:
quantity = np.linalg.inv(models).dot(count)
quantity

array([ 56., 569., 613.])

In [55]:
print('-' * 23)
print('|{:^10}|{:^10}|'.format('Model', 'Quantity'))
print('-'*23)
print('|{:<10}|{:^10}|'.format('Iphone 6', int(quantity[0])))
print('|{:<10}|{:^10}|'.format('Iphone 11', int(quantity[1])))
print('|{:<10}|{:^10}|'.format('Iphone 12', int(quantity[2])))
print('-' * 23)

-----------------------
|  Model   | Quantity |
-----------------------
|Iphone 6  |    56    |
|Iphone 11 |   569    |
|Iphone 12 |   613    |
-----------------------


Составьте каноническое уравнение эллипсоида, проходящего через три точки A,B,CA,B,C

Каноническое уравнение эллипсоида в прямоугольной декартовой системе координат имеет вид:

Задача состоит в определении параметров a^2a, b^2b  и c^2c 

In [58]:
#отримаємо матрицю точок А Б С
points = np.array([[3, 0, 3], [6, 1/4, 0], [1, 1/3, 1]], dtype=float)
points

array([[3.        , 0.        , 3.        ],
       [6.        , 0.25      , 0.        ],
       [1.        , 0.33333333, 1.        ]])

In [59]:
diveder = np.array([1, 1, 1])

In [61]:
decart_points = np.linalg.solve(points, diveder)
decart_points

array([0.08333333, 2.        , 0.25      ])

In [64]:
param = [(1/i)**0.5 for i in decart_points]
param

[3.4641016151377553, 0.7071067811865475, 2.0]

In [65]:
print(f'Параметри: {param}')

Параметри: [3.4641016151377553, 0.7071067811865475, 2.0]


Составьте уравнение параболы проходящей через заданные три точки (1,12), (3,54), (-1,2). Необходимо найти коэффициенты уравнения a,b,ca,b,c


In [66]:
first = np.matrix("1, 1, 1; 9, 3, 1; 1, -1, 1")
first

matrix([[ 1,  1,  1],
        [ 9,  3,  1],
        [ 1, -1,  1]])

In [67]:
second = np.matrix("12;54;2")
second


matrix([[12],
        [54],
        [ 2]])

In [72]:
result = np.linalg.solve(first, second)
result

matrix([[4.],
        [5.],
        [3.]])

In [73]:
print(f'Коефіціент a: {int(result[0])}')
print(f'Коефіціент b: {int(result[1])}')
print(f'Коефіціент c: {int(result[2])}')

Коефіціент a: 4
Коефіціент b: 5
Коефіціент c: 3


Составьте функцию get_polynom, которая по набору точек вида (x_1,y_1),(x_2,y_2), \ldots, (x_{n+1}, y_{n+1})(x1,y1),(x2,y2),…,(x n+1 ,y n+1) будет находить коэффициенты многочлена c_ici.
Таким образом функция принимает список кортежей с координатами и возвращает набор коэффициентов c_0,c_1, \ldots ,c_nc0,c1,…,cn

In [75]:
import numpy as np


def get_polynom(coords):
    a = []
    b = []
    for x, y in coords:
        row = []
        b.append(y)
        for i in range(len(coords)):
            row.append(x**i)
        a.append(row)
    return np.linalg.solve(a, b)

result = get_polynom([(1, 2), (30, 50), (-1, 9)])

In [77]:
print(f'Коэффициенты многочлена: {[i for i in result]}')

Коэффициенты многочлена: [5.333704115684093, -3.5, 0.16629588431590656]
