# *Завдання 1*

У цьому завдання необхідно створити свій власний лінійний класифікатор, а рішення рекомендується оформити як jupyter ноутбука.

Ми колись спостерігали деякі "іграшкові" датасети, які доступні в бібліотеці sklearn. Спробуємо створити лінійну модель для одного такого датасету. Для охочих до повного списку можна знайти [тут](https://scikit-learn.org/stable/datasets/toy_dataset.html) і [тут](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.datasets). Нас же цікавитиме "винний" датасет, інформацію про який можна знайти [тут](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_wine.html#sklearn.datasets.load_wine).

1. Завантажте датасет, виконавши наступний код



In [ ]:
from sklearn.datasets import load_wine

wine_dataset = load_wine()

2. Вивчіть документацію функції [train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html?highlight=train_test_split#sklearn.model_selection.train_test_split). З її допомогою датасет можна розділити на тренувальну та тестову вибірки. Перша потрібна на навчання моделі, а друга - з метою оцінки якості моделі.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import linear_model

wine_dataset = load_wine(as_frame=True)
raw_X, y = load_wine(return_X_y=True)

3. Розділіть wine_dataset на навчальну та тестову вибірки.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(raw_X, y, test_size=0.2, shuffle=True, random_state=0)

4. Навчіть модель на тренувальній вибірці та оцініть її якість на тестовій.

In [ ]:
model = linear_model.RidgeClassifier(fit_intercept = False, max_iter=5000)
model.fit(X_train, y_train)

RidgeClassifier(fit_intercept=False, max_iter=5000)

In [ ]:

model.coef_

array([[-9.18509829e-02,  5.44232865e-02,  4.52344455e-01,
        -8.10973904e-02, -3.99574741e-03, -2.42304632e-01,
         5.23076708e-01,  2.51641172e-02, -2.45788365e-01,
         3.10993920e-02, -3.27652383e-01,  2.00805669e-01,
         1.57601400e-03],
       [ 2.89482988e-02, -1.67968991e-01, -7.10368453e-01,
         7.51010316e-02,  2.93405690e-03,  8.47341728e-02,
        -4.20252988e-02,  2.40782742e-01,  2.92501580e-01,
        -1.44324419e-01,  6.53630566e-01,  9.59114992e-02,
        -1.48386670e-03],
       [-8.68776934e-04,  1.15292384e-01,  2.52962890e-01,
         1.58314560e-03,  3.57695034e-04,  1.52116754e-01,
        -4.57914953e-01, -2.93408588e-01, -6.13895411e-02,
         1.19922940e-01, -3.69398704e-01, -3.12380492e-01,
        -3.40399042e-05]])

In [ ]:
model.score(X_train, y_train)

0.9859154929577465

In [ ]:

model.score(X_test, y_test)

0.9166666666666666

5. Спробуйте повторити кроки 3 і 4 розбивши датасет на навчальну та тестову вибірки в якійсь власній пропорції. Як це вплинуло на якість моделі?

0.9 split = 1 and 0.93 

0.7 split = 0.98 and 0.92

0.6 split = 0.98 and 0.94 

0.5 split = 0.97 and 0.94 

0.2 = 0.98 and 0.91

Найкращій результат -  0.6

# *Завдання 2*

Побудуйте лінійний класифікатор подібно до того, як ми це робили в завданні 1 на датасеті [Іриса Фішера](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html#sklearn.datasets.load_iris). Оформіть рішення у вигляді jupyter ноутбука.

In [ ]:
from sklearn.datasets import load_iris
iris_dataset = load_iris(as_frame=True)
raw_X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(raw_X, y, test_size=0.3, shuffle=True, random_state=0)
model = linear_model.RidgeClassifier(random_state=0,max_iter = 5000)
model.fit(X_train, y_train)

RidgeClassifier(max_iter=5000, random_state=0)

In [ ]:

model.coef_

array([[ 0.19369037,  0.40692179, -0.48163124, -0.1037242 ],
       [-0.0617132 , -0.78117676,  0.34116412, -0.74229765],
       [-0.13197717,  0.37425497,  0.14046711,  0.84602185]])

In [ ]:
model.score(X_train, y_train)

0.8571428571428571

In [ ]:
model.score(X_test, y_test)

0.7555555555555555

5. Спробуйте повторити кроки 3 і 4 розбивши датасет на навчальну та тестову вибірки в якійсь власній пропорції. Як це вплинуло на якість моделі?

0.9 split = 1 and 0.93

0.7 split = 0.98 and 0.92

0.6 split = 0.98 and 0.94

0.5 split = 0.97 and 0.94

0.2 = 0.98 and 0.91

Найкращій результат - 0.6

# *Завдання 3*

У цьому завданні ми маємо побудувати лінійний регресор. На цей раз ми будемо працювати з даними про захворювання на [діабет](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html#sklearn.datasets.load_diabetes). Аналогічно до завдання 1 виконайте такі кроки

1. Завантажте датасет.

In [ ]:
from sklearn.datasets import load_diabetes

2. Розділіть його на тренувальну та тестову вибірки.

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import recall_score, precision_score
from sklearn.model_selection import train_test_split
from sklearn import linear_model

diabetes_dataset = load_diabetes(as_frame=True)
X,y = load_diabetes(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=0)

3. На тренувальній вибірці навчіть лінійну модель.

In [ ]:
regr = linear_model.LinearRegression()
regr.fit(X_train, y_train)

LinearRegression()

4. Оцініть її якість на тестовій вибірці.

In [ ]:
y_pred = regr.predict(X_test)
y_pred

array([238.47145247, 248.93170646, 164.05404165, 120.30794355,
       187.42422054, 259.04865002, 113.55556372, 188.07597044,
       149.49663441, 236.01099949, 172.24629506, 178.88073764,
       109.15751983,  92.13508975, 243.33042043,  87.356971  ,
       155.72606406,  66.99073989, 100.42610442, 218.09422877,
       196.66287912, 161.29832968, 161.70779605, 156.52520454,
       197.88796516, 167.57984206, 120.74478913,  84.83879727,
       192.03728687, 160.60687024, 175.17178362,  84.22833237,
       145.7995542 , 145.97333493, 140.96488953, 197.00421108,
       165.94322494, 190.65906468, 128.22520508, 206.41941223,
        84.35851196, 164.0256504 , 144.1056776 , 184.68355549,
       177.80238966,  74.32855231, 143.3660286 , 138.67726085,
       120.81146113, 234.34252077, 161.94390244,  74.5455476 ,
       154.71905074, 156.78884927, 237.42227096, 174.23053048,
       190.88212635, 118.98373473, 132.20418974, 168.52674824,
       214.74245466, 171.42364091, 157.37409906, 108.86

In [ ]:
regr.score(X_test, y_test)

0.33222203269065176

In [ ]:

print(f"Коефіцієнти :{regr.coef_}\n")
print(f"Середня квадратична похибка: {mean_squared_error(y_test, y_pred)}\n")
print(f"Коефіцієнт детермінації: {r2_score(y_test, y_pred)}")

Коефіцієнти :[ -35.55683674 -243.1692265   562.75404632  305.47203008 -662.78772128
  324.27527477   24.78193291  170.33056502  731.67810787   43.02846824]

Середня квадратична похибка: 3424.316688213733

Коефіцієнт детермінації: 0.33222203269065176


5. Спробуйте повторити кроки 1-4 розбивши датасет на навчальну та тестову вибірки у якійсь власній пропорції. Як це вплинуло на якість моделі?

0.9 split = 1 and 0.93

0.7 split = 0.98 and 0.92

0.6 split = 0.98 and 0.94

0.5 split = 0.97 and 0.94

0.2 = 0.98 and 0.91

Найкращій результат - 0.6